# Generated by Django 2.2.3 on 2019-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20190722_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='group',
        ),
    ]
